project:
  type: website
  output-dir: _site

website:
  title: "Olivia Provance, PhD"
  description: "Olivia Provance, PhD"
  image: "2022_headshot.png"
  navbar:
<<<<<<< HEAD
    background: light
    right:
=======
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
>>>>>>> upstream/main
      - text: About
        href: posts.qmd
      - text: Research
        menu:
<<<<<<< HEAD
          - text: Overview
            href: overview.qmd
          - text: Publications 
            href: publications.qmd
          - text: Presentations, abstracts, and posters
            href: presentations.qmd    
          - text: Funding
            href: projects.qmd                                 
      - text: Running
=======
          - text: List of Publications
            href: publications.qmd
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Grants
            href: projects.qmd                                
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      - text: Outreach
        menu:        
        - text: Presentations
          href: posts.qmd#category=presentation                   
      - text: Group   # Comment the Group part out to remove the Group page
>>>>>>> upstream/main
        href: people.qmd
      - text: CV
        href: files/June_CV.pdf  
      - icon: github
        href: https://oliviaprovance.github.io
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/oliviaprovance/
        aria-label: LinkedIn
  
  page-navigation: true
  
  page-footer: 
    left: "[Olivia Provance](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: " "
    right:  
      - icon: github
        href: https://oliviaprovance.github.io
        target: _blank
      - text: CV
        href: files/June_CV.pdf  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/oliviaprovance/website
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://oliviaprovancephd.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      light: cosmo # your preferred light theme
      dark: darkly        # your preferred dark theme
    color-mode:
      default: light       # or dark, or auto (system preference)
      toggle: true         # show toggle switch in navbar
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

