project:
  type: website
  output-dir: docs

website:
  title: "Olivia Provance, PhD"
  description: "Olivia Provance, PhD"
  image: "2022_headshot.png"
  
  navbar:
   background: light  
  
   right:   
    - text: About
      href: posts.qmd
    - text: Research
      menu:
        - text: Overview
          href: overview.qmd
        - text: Publications  
          href: publications.qmd
        - text: Funding
          href: projects.qmd                                 
    - text: Running
      href: people.qmd
    - text: CV
      href: files/June_CV.pdf  

    - icon: github
      href: https://oliviaprovance.github.io
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/oliviaprovance/
      aria-label: LinkedIn
  
  page-navigation: true
  
  page-footer: 
    left: "[Olivia Provance](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: " "
    right:  
      - icon: github
        href: https://oliviaprovance.github.io
        target: _blank
      - text: CV
        href: files/June_CV.pdf  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/oliviaprovance/website
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://oliviaprovancephd.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      light: cosmo # your preferred light theme
      dark: darkly        # your preferred dark theme
    color-mode:
      default: light       # or dark, or auto (system preference)
      toggle: true         # show toggle switch in navbar
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

