---
title: "Research Overview"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

## Common themes

As a molecular biologist by training my research has been focused on understanding cellular mechanisms of cancer progression. During my PhD training I investigated mechanisms of primary tumor behavior and drug response. During my post-doc training in melanoma I turned to investigate metastatic mechanisms linking the tumor microenvironment, cell intrinsic properties, and clinical outcomes. My work highlights the true complexity of cancer and the importance of understanding the interplay between intrinsic and extrinsic cellular dynamics. 

## Mediators of melanoma brain metastasis

Among solid tumors, melanoma has the highest propensity to metastasize to the brain and melanoma brain metastases (MBM) are responsible for >50% of melanoma related deaths. An abundance of therapies have been developed for patients with extra-cerebral melanoma metastases, but not for patients with melanoma brain metastases (MBM). Only a subset of patients respond to immunotherapy and resistance often develops. These challenges highlight an urgent need to identify regulators of MBM to improve current therapies. However, there is a gap in understanding the brain metastatic process due to an exceedingly limited number of studies and experimental models. My post-doctoral fellowship has been focused on developing and utilizing novel methods to investigate mechanisms of melanoma brain metastases. Two of the main projects are described below. 

### Vasculogenic mimicry in MBM

One way to investigate metastatic mechanisms is to identify intrinsic mechanisms of tumor cells. We identified Vascular mimicry (VM), a form of non angiogenic neovascularization generated by trans-differentiation of tumor cells into vascular endothelial-like cells, is preferred by MBM over traditional angiogenesis. Notably, VM is linked to invasion, early stages of micrometastatic outgrowth, drug resistance and patient overall survival. This study suggests that VM in melanoma brain metastasis could be an important mechanism used by tumor cells when angiogenesis is inadequate to overcome the non-permissive and poorly vascularized microenvironmental pressure of the brain. Additionally, VM may be an underlying cell program unique to a subpopulation of melanoma cells with the competency to not only disseminate to the brain, but to generate metastatic lesions. Moreover, utilization of anti-YAP/TAZ therapy in mouse models of metastatic melanoma significantly inhibits VM formation and prolongs survival, suggesting that targeting VM may be a strategy for treating MBM. Lastly, as angiogenic inhibitors do not inhibit VM formation, we conclude VM formation and blood vessel density are independent, and possibly compensatory mechanisms. My work on this project project has resulted in a first-place poster at the Yale post-doc symposium (2025), and a first-author manuscript. 

### Programmed cell death 4 (PDCD4)

Prior to me joining Dr. Lucia Jilaveanu's research group at Yale University, pre-clinical investigations from the lab identified PLEKHA5, a protein involved in normal brain development, as a mediator of melanoma growth in the brain. Mechanistically, PLEKHA5 downregulates the tumor suppressor molecule, programmed cell death-4 (PDCD4), which we now hypothesize to be a likely suppressor of MBM. PDCD4 is a known tumor suppressor in numerous tissue types as its expression is often lost during the transformation from benign to malignant cancer, PDCD4 has emerged as a regulator of the inflammatory process and our studies suggest a potential role of PDCD4 in T-cell function, though the functional relevance of this finding in melanoma metastasis is unknown. My work on this project included methods such as generating a knockout mouse model, cytokine profiling, multi-color flow cytometry, and numerous molecular biology techniques. While I cannot share the details at the moment as a manuscript submission is under review, my work on this project has resulted in a 2-year fellowship awarded by Yale Center for Clinical Investigation, a Blue Ribbon abstract at the Association of Clinical and Translational Science conference, and a first author manuscript (under review). 


## Novel targets in triple-negative breast cancer

Identification and characterization of novel markers are warranted for development of therapies for triple-negative breast cancer (TNBC) to fulfill a clinically unmet need. As TNBC lacks common receptors used to treat other breast cancer subtypes, therapeutic development is limited.  My doctoral research
efforts focused on characterizing the clinical relevance and mechanism of interferon-induced transmembrane protein-1, IFITM1, in subsets of TNBC. I uncovered the clinical relevance of IFITM1 in TNBC, its tetraspanin mediated mechanism of action, its potential to be used as a biomarker for interferon signaling across subtypes, and for the first time, that IFITM1 is found in TNBC extracellular vesicles. Moreover, I discovered an additional link between tumor cell intrinsic crosstalk between interferon alpha and pro-tumor NFκB signaling in TNBC. Work on this project has resulted in a fellowship awarded by KUMC (Biomedical Research Training Program), a published review article, a published first author manuscript (listed in next section), multiple oral and poster presentations, and Honors Designation for my thesis. 

## FDA drug repurposing for triple negative breast cancer

FDA drug repurposing dramatically reduces time and cost associated with novel drug development. In partnership with the High Throughput Screening Lab at KU-Lawrence as well as the D3ET core at KUMC, I identified that the naturally derived NFκB inhibitor, parthenolide, is cytotoxic to IFITM1 expressing TNBC cells, regulates IFITM1 both in vitro and in vivo, and that loss of IFITM1 enhances parthenolide mediated apoptosis. This work has contributed to an award-winning presentation at the 40th Annual Student Research Forum at KUMC, a regional invited-speaker presentation at the Kansas Capitol resulting in the institutional research award and the biotechnology research award, multiple additional oral and poster presentations, a first author publication in Cancer Letters, and a first-author publication in preparation. 




