---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

1.	Provance, OK, Djureinovic D, Kluger H, Jilaveanu LB. Programmed cell death-4 shapes the melanoma tumor microenvironment and response to immunotherapy. Submitted. 2025. 

2.	Provance OK, Oria VO, Tran TT, Caulfield JI, Zito CR, Aguirre-Ducler A, Schalper KA, Kluger HM, Jilaveanu LB. [Vascular mimicry as a facilitator of melanoma brain metastasis](https://pmc.ncbi.nlm.nih.gov/articles/PMC11026261/#Sec14). Cellular and Molecular Life Sciences. 2024 Apr 18;81(1):188. PMID: 38635031. 


3.	Oria VO, Zhang H, Zito CR, Rane CK, Ma XY, Provance OK, Tran TT, Adeniran A, Kluger Y, Sznol M, Bosenberg MW, Kluger HM, Jilaveanu LB. [Coupled fibromodulin and SOX2 signaling as a critical regulator of distant metastasis initiation in melanoma](https://pmc.ncbi.nlm.nih.gov/articles/PMC9226089/). Cellular and Molecular Life Sciences. 2022 Jun 23;79(7):377. PMID: 35737114. 


4.	Provance OK, Geanes ES, Lui AJ, Holloran SH, Roy A, Gunewardena S, Weir S, Lewis-Wambi J, [Disrupting interferon-alpha and NF-kappaB crosstalk suppresses IFITM1 expression attenuating triple-negative breast cancer progression](https://pubmed.ncbi.nlm.nih.gov/34022283/). Cancer Letters. 2021 Aug 28;514:12-29. Epub 2021 May 20. PMID: 34022283.


5.	Provance OK, Lewis-Wambi J, [Deciphering the role of interferon alpha signaling and microenvironment crosstalk in inflammatory breast cancer](https://pubmed.ncbi.nlm.nih.gov/31060575/). Breast Cancer Research. 2019 May 6;21(1):59. PMID: 31060575

6.	Provance OK, Won HS, Escher TE, Lewis-Wambi J. IFITM1 mediated induction of XBP1 regulates atorvastatin response in triple negative breast cancer cells. In preparation.



